# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceJeux.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

from PyQt5.QtMultimedia import *
from PyQt5.QtMultimediaWidgets import *

from CommWorker import CommWorker
from algoRPC import AlgoRPC

import cv2


class UiManUSludumInterface(object):

    # Variable globale du décompte
    nbDecompte = 8
    count = 0
    start = False
    gameRunning = False

    # Variable globale de statistiques
    AIwin = 0
    Humanwin = 0
    nombreR = 0
    nombreP = 0
    nombreC = 0

    def setup_ui(self, ManUS_ludum_Interface):
        """
        Initialisation du UI et de toutes ces composantes

        :param ManUS_ludum_Interface:
        :return:
        """

        # Initialisation de la fenêtre principale
        ManUS_ludum_Interface.setObjectName("ManUS_ludum_Interface")
        ManUS_ludum_Interface.resize(1620, 958)
        self.centralwidget = QtWidgets.QWidget(ManUS_ludum_Interface)
        self.centralwidget.setObjectName("centralwidget")

        # Fil d'exécution de la communication
        self.commWorker = CommWorker(comPort="COM8")
        self.commWorker.start()
        self.commWorker.textReceived.connect(self.showCommMessage)

        # Fil d'exécution de la vision et de l'algorithme de jeux
        self.visionRPC = AlgoRPC()
        self.visionRPC.frameToDisplay.connect(self.rafraichirCam)
        self.visionRPC.roundData.connect(self.showRoundData)
        self.visionRPC.gameWinner.connect(self.updateWinnerStats)
        self.visionRPC.start()

        # Initialisation de la section de la caméra
        self.camera = QtWidgets.QGroupBox(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(730, 85, 880, 610))
        self.camera.setObjectName("camera")

        # Widget qui contient la caméra
        self.camHolder = QtWidgets.QTabWidget(self.camera)
        self.camHolder.setGeometry(QtCore.QRect(10, 10, 860, 590))
        self.camHolder.setTabPosition(QtWidgets.QTabWidget.South)
        self.camHolder.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.camHolder.setUsesScrollButtons(False)
        self.camHolder.setObjectName("camHolder")

        self.tab = QtWidgets.QWidget()
        self.videoimage = QtWidgets.QLabel(self.tab)
        self.videoimage.setGeometry(QtCore.QRect(10, 10, 860, 590))

        self.available_cameras = QCameraInfo.availableCameras()

        self.camHolder.addTab(self.videoimage, self.available_cameras[0].description())

        # Initialisation de l'entête
        self.header = QtWidgets.QGroupBox(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(10, 10, 1600, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.header.setFont(font)
        self.header.setTitle("")
        self.header.setFlat(False)
        self.header.setObjectName("header")

        # Bouton qui permet de lancer le décompte (débute la partie)
        self.boutonLancementJeux = QtWidgets.QPushButton(self.header)
        self.boutonLancementJeux.setGeometry(QtCore.QRect(10, 10, 700, 50))
        self.boutonLancementJeux.setObjectName("boutonLancementJeux")
        self.boutonLancementJeux.clicked.connect(self.debut_decompte)

        # Bouton qui fait apparaître un popup qui explique comment jouer
        self.boutonInfo = QtWidgets.QPushButton(self.header)
        self.boutonInfo.setGeometry(QtCore.QRect(1540, 10, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.boutonInfo.setFont(font)
        self.boutonInfo.setObjectName("boutonInfo")
        self.boutonInfo.clicked.connect(self.show_popup)

        # Nom du projet (label)
        self.titre = QtWidgets.QLabel(self.header)
        self.titre.setGeometry(QtCore.QRect(720, 10, 810, 50))
        font = QtGui.QFont()
        font.setPointSize(37)
        self.titre.setFont(font)
        self.titre.setAutoFillBackground(False)
        self.titre.setAlignment(QtCore.Qt.AlignCenter)
        self.titre.setObjectName("titre")

        # Initialisation de la section de contrôle du robot
        self.robot = QtWidgets.QGroupBox(self.centralwidget)
        self.robot.setGeometry(QtCore.QRect(10, 85, 350, 570))
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.robot.setFont(font)
        self.robot.setTitle("")
        self.robot.setObjectName("robot")

        # Nom de la section (label)
        self.titreContMain = QtWidgets.QLabel(self.robot)
        self.titreContMain.setGeometry(QtCore.QRect(10, 10, 330, 90))
        self.titreContMain.setAutoFillBackground(True)
        self.titreContMain.setFrameShape(QtWidgets.QFrame.Box)
        self.titreContMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titreContMain.setLineWidth(2)
        self.titreContMain.setAlignment(QtCore.Qt.AlignCenter)
        self.titreContMain.setObjectName("titreContMain")

        # Bouton qui indique à la main de retourner à sa position initiale
        self.boutonRobotInit = QtWidgets.QPushButton(self.robot)
        self.boutonRobotInit.setGeometry(QtCore.QRect(35, 105, 280, 85))
        self.boutonRobotInit.setObjectName("boutonRobotInit")
        self.boutonRobotInit.clicked.connect(lambda: self.commWorker.sendToArduino("I"))

        # Bouton qui indique à la main de jouer roche
        self.boutonRobotRoche = QtWidgets.QPushButton(self.robot)
        self.boutonRobotRoche.setGeometry(QtCore.QRect(35, 195, 280, 85))
        self.boutonRobotRoche.setObjectName("boutonRobotRoche")
        self.boutonRobotRoche.clicked.connect(lambda: self.commWorker.sendToArduino("R"))

        # Bouton qui indique à la main de jouer papier
        self.boutonRobotPapier = QtWidgets.QPushButton(self.robot)
        self.boutonRobotPapier.setGeometry(QtCore.QRect(35, 285, 280, 85))
        self.boutonRobotPapier.setObjectName("boutonRobotPapier")
        self.boutonRobotPapier.clicked.connect(lambda: self.commWorker.sendToArduino("P"))

        # Bouton qui indique à la main de jouer ciseaux
        self.boutonRobotCiseaux = QtWidgets.QPushButton(self.robot)
        self.boutonRobotCiseaux.setGeometry(QtCore.QRect(35, 375, 280, 85))
        self.boutonRobotCiseaux.setObjectName("boutonRobotCiseaux")
        self.boutonRobotCiseaux.clicked.connect(lambda: self.commWorker.sendToArduino("C"))

        # Bouton qui arrête la main (cold stop des moteurs)
        self.boutonRobotAU = QtWidgets.QPushButton(self.robot)
        self.boutonRobotAU.setGeometry(QtCore.QRect(35, 465, 280, 85))
        self.boutonRobotAU.setObjectName("boutonRobotAU")
        self.boutonRobotAU.clicked.connect(lambda: self.commWorker.sendToArduino("A"))

        # Initialisation de la section d'affichage des données
        self.donnees = QtWidgets.QGroupBox(self.centralwidget)
        self.donnees.setGeometry(QtCore.QRect(370, 85, 350, 570))
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.donnees.setFont(font)
        self.donnees.setTitle("")
        self.donnees.setObjectName("donnees")

        # Nom de la section (label)
        self.titreDonnees = QtWidgets.QLabel(self.donnees)
        self.titreDonnees.setGeometry(QtCore.QRect(10, 10, 330, 90))
        self.titreDonnees.setAutoFillBackground(True)
        self.titreDonnees.setFrameShape(QtWidgets.QFrame.Box)
        self.titreDonnees.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titreDonnees.setLineWidth(2)
        self.titreDonnees.setAlignment(QtCore.Qt.AlignCenter)
        self.titreDonnees.setObjectName("titreDonnees")

        self.AIlastMoveLabel = QtWidgets.QLabel(self.donnees)
        self.AIlastMoveLabel.setGeometry(QtCore.QRect(35, 130, 285, 90))
        self.AIlastMoveLabel.setObjectName("AIlastMoveLabel")

        self.AIlastMove = QtWidgets.QLabel(self.donnees)
        self.AIlastMove.setGeometry(QtCore.QRect(35, 175, 285, 90))
        self.AIlastMove.setObjectName("AIlastMove")

        self.HumanlastMoveLabel = QtWidgets.QLabel(self.donnees)
        self.HumanlastMoveLabel.setGeometry(QtCore.QRect(35, 230, 285, 90))
        self.HumanlastMoveLabel.setObjectName("HumanlastMoveLabel")

        self.HumanlastMove = QtWidgets.QLabel(self.donnees)
        self.HumanlastMove.setGeometry(QtCore.QRect(35, 275, 285, 90))
        self.HumanlastMove.setObjectName("HumanlastMove")

        self.gagnantMancheLabel = QtWidgets.QLabel(self.donnees)
        self.gagnantMancheLabel.setGeometry(QtCore.QRect(35, 330, 285, 90))
        self.gagnantMancheLabel.setObjectName("gagnantMancheLabel")

        self.gagnantManche = QtWidgets.QLabel(self.donnees)
        self.gagnantManche.setGeometry(QtCore.QRect(35, 375, 285, 90))
        self.gagnantManche.setObjectName("gagnantManche")

        # Initialisation de la section Statistiques
        self.statistiques = QtWidgets.QGroupBox(self.centralwidget)
        self.statistiques.setGeometry(QtCore.QRect(10, 659, 710, 271))
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.statistiques.setFont(font)
        self.statistiques.setTitle("")
        self.statistiques.setObjectName("statistiques")

        # Bouton qui réinitialise les statistiques
        self.boutonStatsReset = QtWidgets.QPushButton(self.statistiques)
        self.boutonStatsReset.setGeometry(QtCore.QRect(10, 10, 150, 40))
        self.boutonStatsReset.setObjectName("boutonStatsReset")
        self.boutonStatsReset.clicked.connect(self.reinitialisationStats)

        # Nom de la section (label)
        self.titreStats = QtWidgets.QLabel(self.statistiques)
        self.titreStats.setGeometry(QtCore.QRect(170, 10, 531, 40))
        self.titreStats.setAutoFillBackground(True)
        self.titreStats.setFrameShape(QtWidgets.QFrame.Box)
        self.titreStats.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titreStats.setLineWidth(2)
        self.titreStats.setAlignment(QtCore.Qt.AlignCenter)
        self.titreStats.setObjectName("titreStats")

        # Texte des stats de l'AI (label)
        self.statsAIwin = QtWidgets.QLabel(self.statistiques)
        self.statsAIwin.setGeometry(QtCore.QRect(10, 90, 510, 25))
        self.statsAIwin.setObjectName("statsAIwin")

        # Indicateur numérique du nombre de victoire de l'AI
        self.nbAiWin = QtWidgets.QLCDNumber(self.statistiques)
        self.nbAiWin.setGeometry(QtCore.QRect(530, 90, 170, 25))
        self.nbAiWin.setObjectName("nbAiWin")

        # Indicateur numérique du nombre de victoire de l'humain
        self.nbHumWin = QtWidgets.QLCDNumber(self.statistiques)
        self.nbHumWin.setGeometry(QtCore.QRect(530, 140, 170, 25))
        self.nbHumWin.setObjectName("nbHumWin")

        # Texte des stats de l'humain (label)
        self.statsHumWin = QtWidgets.QLabel(self.statistiques)
        self.statsHumWin.setGeometry(QtCore.QRect(10, 140, 510, 25))
        self.statsHumWin.setObjectName("statsHumWin")

        # Indicateur numérique du pourcentage de roche
        self.pourcentRoche = QtWidgets.QLCDNumber(self.statistiques)
        self.pourcentRoche.setGeometry(QtCore.QRect(10, 200, 75, 50))
        self.pourcentRoche.setSmallDecimalPoint(False)
        self.pourcentRoche.setObjectName("pourcentRoche")

        # Texte des stats pourcentage de roche (label)
        self.statsRoche = QtWidgets.QLabel(self.statistiques)
        self.statsRoche.setGeometry(QtCore.QRect(95, 200, 125, 50))
        self.statsRoche.setObjectName("statsRoche")

        # Texte des stats pourcentage de papier (label)
        self.statsPapier = QtWidgets.QLabel(self.statistiques)
        self.statsPapier.setGeometry(QtCore.QRect(335, 200, 125, 50))
        self.statsPapier.setObjectName("statsPapier")

        # Indicateur numérique du pourcentage de papier
        self.pourcentPapier = QtWidgets.QLCDNumber(self.statistiques)
        self.pourcentPapier.setGeometry(QtCore.QRect(250, 200, 75, 50))
        self.pourcentPapier.setSmallDecimalPoint(False)
        self.pourcentPapier.setObjectName("pourcentPapier")

        # Texte des stats pourcentage de ciseaux (label)
        self.statsCiseaux = QtWidgets.QLabel(self.statistiques)
        self.statsCiseaux.setGeometry(QtCore.QRect(575, 200, 125, 50))
        self.statsCiseaux.setObjectName("statsCiseaux")

        # Indicateur numérique du pourcentage de ciseaux
        self.pourcentCiseaux = QtWidgets.QLCDNumber(self.statistiques)
        self.pourcentCiseaux.setGeometry(QtCore.QRect(490, 200, 75, 50))
        self.pourcentCiseaux.setSmallDecimalPoint(False)
        self.pourcentCiseaux.setObjectName("pourcentCiseaux")

        # Initialisation de la section du décompte
        self.decompte = QtWidgets.QGroupBox(self.centralwidget)
        self.decompte.setGeometry(QtCore.QRect(730, 700, 880, 230))
        self.decompte.setObjectName("decompte")

        # Texte du décompte
        self.txtDecompte = QtWidgets.QLabel(self.decompte)
        self.txtDecompte.setGeometry(QtCore.QRect(10, 20, 860, 200))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txtDecompte.setFont(font)
        self.txtDecompte.setAutoFillBackground(False)
        self.txtDecompte.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDecompte.setObjectName("txtDecompte")

        # Initialisation de la barre de statut
        ManUS_ludum_Interface.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ManUS_ludum_Interface)
        self.statusbar.setObjectName("statusbar")
        ManUS_ludum_Interface.setStatusBar(self.statusbar)

        # Écriture des étiquettes et connexion des fenêtres
        self.retranslate_ui(ManUS_ludum_Interface)
        QtCore.QMetaObject.connectSlotsByName(ManUS_ludum_Interface)

    def showCommMessage(self, messageReceived:str):
        """
        Impression à la console de message retourné par l'arduino

        :param messageReceived:
        :return:
        """
        print(messageReceived)

    def updateWinnerStats(self, gameWinner: str):
        """
        Rafraîchi l'affichage statistique des victoires

        :param gameWinner:
        :return:
        """
        if self.gameRunning:
            if gameWinner == "u":
                self.Humanwin += 1
                self.nbHumWin.display(self.Humanwin)
                pass
            elif gameWinner == "m":
                self.AIwin += 1
                self.nbAiWin.display(self.AIwin)
                pass
            else:
                pass

    def showRoundData(self, roundDataList:list):
        """
        Rafraîchi l'affichage des statistiques selon les informations de la manche

        :param roundDataList:
        :return:
        """
        if self.gameRunning:
            if roundDataList[0] == "rock":
                self.HumanlastMove.setText("Roche")
                self.nombreR += 1
            elif roundDataList[0] == "paper":
                self.HumanlastMove.setText("Papier")
                self.nombreP += 1
            elif roundDataList[0] == "scissor":
                self.HumanlastMove.setText("Ciseaux")
                self.nombreC += 1

            if roundDataList[1] == "rock":
                self.commWorker.sendToArduino("R")
                self.AIlastMove.setText("Roche")
            elif roundDataList[1] == "paper":
                self.commWorker.sendToArduino("P")
                self.AIlastMove.setText("Papier")
            elif roundDataList[1] == "scissor":
                self.commWorker.sendToArduino("C")
                self.AIlastMove.setText("Ciseaux")

            if roundDataList[2] == "User":
                self.gagnantManche.setText("Vous")
            elif roundDataList[2] == "ManUS":
                self.gagnantManche.setText("ManUS")
            elif roundDataList[2] == "Tie":
                self.gagnantManche.setText("Égalité")

            pourcentR = 100 * self.nombreR / (self.nombreR + self.nombreP + self.nombreC)
            self.pourcentRoche.display(pourcentR)

            pourcentP = 100 * self.nombreP / (self.nombreR + self.nombreP + self.nombreC)
            self.pourcentPapier.display(pourcentP)

            pourcentC = 100 * self.nombreC / (self.nombreR + self.nombreP + self.nombreC)
            self.pourcentCiseaux.display(pourcentC)

    def rafraichirCam(self, frametodisplay):
        """
        Rafraîchi l'affichage de la caméra à chaque fois que le fil d'exécution de la vision émet des données

        :param frametodisplay:
        :return:
        """
        image = QtGui.QImage(frametodisplay, frametodisplay.shape[1], \
                             frametodisplay.shape[0], frametodisplay.shape[1] * 3, QtGui.QImage.Format_RGB888).rgbSwapped()
        pix = QtGui.QPixmap(image)
        self.videoimage.setPixmap(pix)

    def retranslate_ui(self, ManUS_ludum_Interface):
        """
        Fonction qui écrit le texte des différents composants de l'interface
        (fonction de QtDesigner)

        :param ManUS_ludum_Interface:
        :return:
        """
        _translate = QtCore.QCoreApplication.translate
        ManUS_ludum_Interface.setWindowTitle(_translate("ManUS_ludum_Interface", "ManUS ludum Interface"))
        self.boutonLancementJeux.setText(_translate("ManUS_ludum_Interface", "Commencer la partie"))
        self.titre.setText(_translate("ManUS_ludum_Interface", "ManUS ludum"))
        self.boutonInfo.setText(_translate("ManUS_ludum_Interface", "i"))
        self.titreContMain.setText(_translate("ManUS_ludum_Interface", "Contrôle de la main"))
        self.boutonRobotInit.setText(_translate("ManUS_ludum_Interface", "Position Initiale"))
        self.boutonRobotRoche.setText(_translate("ManUS_ludum_Interface", "Roche"))
        self.boutonRobotPapier.setText(_translate("ManUS_ludum_Interface", "Papier"))
        self.boutonRobotCiseaux.setText(_translate("ManUS_ludum_Interface", "Ciseaux"))
        self.boutonRobotAU.setText(_translate("ManUS_ludum_Interface", "Arrêt d'urgence"))

        #self.boutonHumainRoche.setText(_translate("ManUS_ludum_Interface", "Roche"))
        self.titreDonnees.setText(_translate("ManUS_ludum_Interface", "Données de la manche"))
        #self.boutonHumainCiseaux.setText(_translate("ManUS_ludum_Interface", "Ciseaux"))
        #self.boutonHumainPapier.setText(_translate("ManUS_ludum_Interface", "Papier"))
        self.AIlastMoveLabel.setText(_translate("ManUS_ludum_Interface", "Dernier coup de ManUS :"))
        self.HumanlastMoveLabel.setText(_translate("ManUS_ludum_Interface", "Votre dernier coup :"))
        self.gagnantMancheLabel.setText(_translate("ManUS_ludum_Interface", "Gagnant de la manche :"))

        self.boutonStatsReset.setText(_translate("ManUS_ludum_Interface", "Réinitialisation"))
        self.titreStats.setText(_translate("ManUS_ludum_Interface", "Statistiques de jeux"))
        self.statsAIwin.setText(_translate("ManUS_ludum_Interface", "Nombre de manche gagnée par ManUS :"))
        self.statsHumWin.setText(_translate("ManUS_ludum_Interface", "Nombre de manche que vous avez gagnée :"))
        self.statsRoche.setText(_translate("ManUS_ludum_Interface", "% Roche"))
        self.statsPapier.setText(_translate("ManUS_ludum_Interface", "% Papier"))
        self.statsCiseaux.setText(_translate("ManUS_ludum_Interface", "% Ciseaux"))
        self.txtDecompte.setText(_translate("ManUS_ludum_Interface", "En Attente"))

    @staticmethod
    def show_popup():
        """
        Fonction qui affiche le popup d'information du jeux

        :return:
        """
        msg = QMessageBox()
        msg.setWindowTitle("Comment jouer?")
        msg.setText("   Pour lancer la partie cliquez sur 'Commencer la partie' .\n"
                    "   Fiez-vous ensuite au décompte en-bas à droite\n"
                    "   et jouez votre coup sur 'À vous de jouer' .\n"
                    "   Vous aurez 2 secondes pour jouer!\n")
        msg.setIcon(QMessageBox.Question)

        msg.exec_()

    def reinitialisationStats(self):
        """
        Réinitialisation des variables et de l'affichage des statistiques
        :return:
        """
        self.AIwin = 0
        self.Humanwin = 0
        self.nombreR = 0
        self.nombreP = 0
        self.nombreC = 0

        self.nbAiWin.display(self.AIwin)
        self.nbHumWin.display(self.Humanwin)
        self.pourcentRoche.display(self.nombreR)
        self.pourcentPapier.display(self.nombreP)
        self.pourcentCiseaux.display(self.nombreC)

    def texte_decompte(self):
        """
        Fonction qui change le texte de l'étiquette de décompte selon
        l'interval de temps choisi au setup

        :return:
        """
        _translate = QtCore.QCoreApplication.translate

        if self.start:
            if self.count < 1:
                self.txtDecompte.setText(_translate("ManUS_ludum_Interface", "En Attente"))
                self.count = self.nbDecompte
                self.start = False
                self.gameRunning = False
            elif self.count == 8:
                self.txtDecompte.setText(_translate("ManUS_ludum_Interface", "Prêt?"))
                self.count = self.count - 1
                self.commWorker.sendToArduino("I")
            elif self.count == 7:
                self.txtDecompte.setText(_translate("ManUS_ludum_Interface", "C'est parti!"))
                self.count = self.count - 1
            elif self.count == 6:
                self.txtDecompte.setText(_translate("ManUS_ludum_Interface", "Roche"))
                self.count = self.count - 1
            elif self.count == 5:
                self.txtDecompte.setText(_translate("ManUS_ludum_Interface", "Papier"))
                self.count = self.count - 1
            elif self.count == 4:
                self.txtDecompte.setText(_translate("ManUS_ludum_Interface", "Ciseaux"))
                self.count = self.count - 1
            elif self.count == 3:
                self.txtDecompte.setText(_translate("ManUS_ludum_Interface", "À vous de jouer!"))
                self.count = self.count - 1
                self.gameRunning = True
            elif self.count == 2:
                self.count = self.count - 1
            elif self.count == 1:
                self.count = self.count - 1

    def debut_decompte(self):
        """
        Fonction qui débute le chronomètre du décompte et réinitialise les variables de jeux

        :return:
        """
        self.start = True
        self.gameRunning = False
        self.count = self.nbDecompte


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    ManUS_ludum_Interface = QtWidgets.QMainWindow()
    ui = UiManUSludumInterface()
    ui.setup_ui(ManUS_ludum_Interface)
    ManUS_ludum_Interface.show()

    # Timer pour le décompte
    timer = QTimer()
    timer.timeout.connect(ui.texte_decompte)
    timer.start(750)

    sys.exit(app.exec())
